version: '3.1'

services:
  carla:
    build:
      context: .
      dockerfile: ./Dockerfile_1804
      args:
        BASE_DIST: "ubuntu20.04"
        CUDA_VERSION: "11.4.2"
        VULKAN_SDK_VERSION: "1.3.224.1"
    command: bash -c "~/setup.sh"
    stdin_open: true
    tty: true
    # edit this to map carla and unreal engine
    volumes:
      - "${UE4_PATH}:${DOCKER_HOME}/UnrealEngine"
      - "${CARLA_PATH}:${DOCKER_HOME}/carla"
      - '/tmp/.X11-unix/:/tmp/.X11-unix/'
      - '~/.Xauthority/:${DOCKER_HOME}/.Xauthority'
      - "/usr/bin/prime-run:/usr/bin/prime-run"
      - "~/dotfiles:${DOCKER_HOME}/dotfiles"

    user: "1000:1000"

    privileged: true

    environment:
      DISPLAY: ":0"
      UE4_ROOT: "${DOCKER_HOME}/UnrealEngine"

    network_mode: host

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
