FROM nvidia/vulkan:1.1.121-cuda-10.1-beta.0-ubuntu18.04

# configs
ARG user=carla
ARG passwd=carla
ARG home=/home/$user

# install basic softwares and add user
# prevent interactive input prompts
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A4B469963BF863CC && \
    apt-get update && \
    apt-get install -y xauth zsh git curl glmark2 lsb-release gnupg2 sudo neovim && \
    useradd -m -s /bin/bash $user  && \
    echo $user:$passwd | chpasswd

# prepare environment
RUN apt-get update && \
    apt-get install -y wget software-properties-common && \
    add-apt-repository ppa:ubuntu-toolchain-r/test && \
    wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add - && \
    apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main" && \
    apt-get update && \
    apt-get -y install build-essential clang-8 lld-8 g++-7 cmake ninja-build libvulkan1 python python-pip python-dev python3-dev python3-pip libpng-dev libtiff5-dev libjpeg-dev tzdata sed curl unzip autoconf libtool rsync libxml2-dev git libxrandr2 x11-xserver-utils aria2 && \
    update-alternatives --install /usr/bin/clang++ clang++ /usr/lib/llvm-8/bin/clang++ 180 && \
    update-alternatives --install /usr/bin/clang clang /usr/lib/llvm-8/bin/clang 180 && \
    pip3 install --upgrade pip && \
    pip install --upgrade pip && \
    pip install --user setuptools distro wheel && \
    pip3 install --user -Iv setuptools==47.3.1 && \
    pip3 install --user distro wheel auditwheel && \
    rm -rf /var/lib/apt/lists/*

# copy setup file
COPY --chmod=777 setup.sh $home/setup.sh
